### ISSUE TITLE
Set up LocalEGA Docker CI on CSC OpenShift infrastructure

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/LocalEGA#101]
Setting up localEGA on the OpenShift server for testing. The application, a set of docker containers with various ega services will be set up. A testing script will simulate the procedures with data uploading and ingestion.

**Comment by dtitov** [comment]
Still waiting for providing access to the infrastructure from Olli Tourunen.

**Comment by dtitov** [comment]
Well, I've played a bit with provided infrastructure last days and it seems that it doesn't suit our needs (or at least this particular task).

OpenShift Origin appeared to be backed by [Kubernetes](https://kubernetes.io/). And what we want to do is to implement [automated Docker deployment](https://www.docker.com/use-cases/cicd). These inputs seem to be incompatible to me, taking into account that we use `docker-compose`. I mean, we are able to deploy stand-alone Docker images there, but not the whole system at once (at least without some hacks). And things are getting even more complicated because of fact that it's not even plain Kubernetes: Origin wraps it in it's own way...  

So my question is: is it a requirement to use OpenShift? We could use some OpenStack infrastructure (e.g. http://www.uh-iaas.no/) and deploy [Docker Swarm](https://docs.docker.com/engine/swarm/key-concepts/) there. Otherwise we'll have to implement Kubernetes deployment separately, perhaps via [Terraform](https://www.terraform.io/docs/providers/kubernetes/index.html) as well. But I'm not sure if it's even possible as it's not native Kubernetes, as I have already mentioned. Anyway then it will have nothing in common with Docker.

Please, correct me, if I misunderstand something here.

**Comment by silverdaz** [comment]
We don't need to use docker-compose, we are free to use anything else. However, we do have an Openshift environment, so we'd better use it. If it requires anything else, we're open for suggestions and fixes/solutions.

Our colleagues on the [Phenomenal project](https://github.com/phnmnl) use Kubernetes a lot and have deployable infrastructures there, so it's surely doable.
Wanna check their project? Ping Anders or Marco if you're interested.

**Comment by dtitov** [comment]
Thanks for your comment. 

> We don't need to use docker-compose, we are free to use anything else.

Then we probably should rethink this task, because, AFAIU, if we are bound to OpenShift, then it's not about Docker-pipeline anymore - it should be something else. And we need to figure out what exactly. 

> Our colleagues on the Phenomenal project use Kubernetes a lot and have deployable infrastructures there, so it's surely doable.

Cool, but do they use OpenShift? I found this in their readme: "This page will guide you to set up a PhenoNeNal CRE on Amazon, Google Cloud or in a public or private OpenStack environment".

In any case, if there are no objections, I can try to make small proof-of-concept based on UH IaaS OpenStack with Swarm. Maybe you will like it :)

**Comment by silverdaz** [comment]
Sure! Go ahead! Sounds interesting.

**Comment by juhtornr** [comment]
It is possible to convert docker-compose setup to Kubernetes/Openshift (at least in some extent):

https://kubernetes.io/docs/tools/kompose/user-guide/
https://lists.openshift.redhat.com/openshift-archives/dev/2016-May/msg00021.html

We discussed with @dtitov that I'll try to do that.

**Comment by nanjiangshu** [comment]
@juhtornr, yes but with docker-compose version 2. There is some problem for the version 3+.

**Comment by silverdaz** [comment]
What are the parts that do not work with version 3+ ? 
Maybe we could do without, and version 2 is enough?

**Comment by dtitov** [comment]
I had several issues I haven't been able to fight with this tool:

- The first one was that this tool doesn't "understand" 3.2 version of docker-compose file. So I had to downgrade it manually. 
- Then there were some issues with volumes and mounting.
- And finally with entrypoints. Because currently we have entrypoints as shell-scripts mounted onto each container. And that didn't work in my experience (with this tool).

**Comment by nanjiangshu** [comment]
When I checked the yml for for openshift after running 

`oc import docker-compose -f docker-compose.yml -o yaml`

It seems the ENVs defined in the docker-compose file (or the in the `.env` file) are all empty in the yaml file for the openshift

**Comment by silverdaz** [comment]
Can you use some bash env variables in OpenShift?
If so, convert the `.env` file into env variables that docker will read.

**Comment by nanjiangshu** [comment]
That should be doable, to define them in the jenkinsfile

**Comment by silverdaz** [comment]
Then, go ahead, skip the `.env` file, that only defines those variables, to make the whole setup configurable and fix whatever you need about the mount points or the shell entrypoints.

Note: Be aware of the [differences between _bracketed_ and _string_ version of CMD](https://docs.docker.com/engine/reference/builder/#cmd)

Try to make the gpg passphrase included only in the keys container, not all of them. (I mean: don't put it in some env variable that ends up in all the containers because it was easier for you)

**Comment by dtitov** [comment]
OK, everything seems to work fine on OpenStack (http://www.uh-iaas.no/).

Jenkins: http://158.39.77.10/job/LocalEGA/ Credentials: test/test

Build is triggered when changes are pushed to the fork repo (https://github.com/dtitov/LocalEGA/). 

Basically it contains of three steps (not to dig into the details): deploy LocalEGA locally (at the Jenkins instance), perform tests on this deployment, deploy LocalEGA to staging environment (remote instance spawned by `docker-machine`) if tests passed. Current staging instance address is: http://158.39.75.71:9000/

Currently "tests" step contain only one sample test: sleep thread for a minute and then `curl` lega_frontend (localhost:9000) to check if it's serving content. 

To achieve I had to make some changes to ega.yml and my bootstrap Dockerfile. Updated file can be found here: https://github.com/dtitov/LocalEGA/tree/ci/docker

If this pipeline looks fine, I can make it work with the main repo and it's master branch.

**Comment by dtitov** [comment]
Hi, everyone.

Made it work today with `master` branch of LocalEGA [repo](https://github.com/NBISweden/LocalEGA/) with latest bootstrapping changes from Fred. There's no web-hook yet, so the build has to be triggered manually.

Everything works fine, except for this issue: https://github.com/NBISweden/LocalEGA/issues/127 It doesn't block testing on Jenkins (I've applied WA), but it blocks remote deployment (frontend fails to startup). I will try take a look this week.
