### ISSUE TITLE
Read data from LocalEGA vault by the EGA-DATA-API

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/LocalEGA#236]
Hook up the EGA-DATA-API and LocalEGA so that data files in the LocalEGA vault can be read via the EGA-DATA-API for a given user authenticated by Elixir AAI

**Comment by dtitov** [comment]
I have created a sample code for decryption of vault-files: https://gist.github.com/dtitov/efc93ff3df26c9d8491dbce8fb78b7f1

It works, I tested it on a real file. There's only one thing needs to be changed: I need a private key (`ega.sec` file) in a PKCS8 format. Currently, we have it in PKCS1 format. Here's the difference: https://superuser.com/questions/606215/openssl-pkcs8-default-format-gives-rsa-private-key

So we need to add something like `openssl pkcs8 -topk8 -inform PEM -outform PEM -in ega.sec -out ega2.sec -nocrypt` to the `instance.sh` to have both.

Now I need to find a place where to plug this code in :)

**Comment by silverdaz** [comment]
Central EGA has already done something similar in their code (also in Java).
So I asked Oscar to review the code.
He might have some good pointers.

**Comment by dtitov** [comment]
After some deeper investigation of data-out API, I can conclude, that the code, unfortunately, is very messy. It had a bunch of bugs I've fixed already and who knows how many more are still there... And what's also annoying: some things are simply missing there (TODO's in code). So I'm starting to doubt the benefits of using that solution. Of course, I can try to bring it to life and make it work somehow, but it's not simply "extend one class" as we thought before - it's much more of work... And this amount of efforts (according to my modest estimations) is comparable to creating some fresh well-designed and working solution (perhaps, with Vault under the hood). But, of course, in that case, we won't have dev-support from EBI, so that's why it's doubtful (do we have any support now, btw?)...

Anyway, I created a small prototype for decryption and retrieving files from the vault: https://youtu.be/_jE6glpEQj4 Please, take a look and then we can discuss this at the Friday's meeting.

**Comment by silverdaz** [comment]
Sounds good 👍 

Note: we had already our own implementation (in Python).
And yes, it's probably interesting to leverage the code of A Senf which already is working in 3 different places.
